
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author elva
 */
public class Interfaz_grafos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz_grafos.class.getName());

    /**
     * Creates new form Interfaz_grafos
     */
    public Interfaz_grafos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        mostrar_dic = new javax.swing.JTextArea();
        busq_gen = new javax.swing.JCheckBox();
        busq_esp = new javax.swing.JCheckBox();
        guardar_dic = new javax.swing.JButton();
        cargar_dic = new javax.swing.JButton();
        arbol_bfs = new javax.swing.JButton();
        palabra_arbol = new javax.swing.JComboBox<>();
        palabra_busq = new javax.swing.JTextField();
        DFS = new javax.swing.JButton();
        BFS = new javax.swing.JButton();
        letra1 = new javax.swing.JLabel();
        letra2 = new javax.swing.JLabel();
        letra3 = new javax.swing.JLabel();
        letra4 = new javax.swing.JLabel();
        letra5 = new javax.swing.JLabel();
        letra6 = new javax.swing.JLabel();
        letra7 = new javax.swing.JLabel();
        letra8 = new javax.swing.JLabel();
        letra9 = new javax.swing.JLabel();
        letra10 = new javax.swing.JLabel();
        letra11 = new javax.swing.JLabel();
        letra12 = new javax.swing.JLabel();
        letra13 = new javax.swing.JLabel();
        letra14 = new javax.swing.JLabel();
        letra15 = new javax.swing.JLabel();
        letra16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        mostrar_dic.setColumns(20);
        mostrar_dic.setRows(5);
        jScrollPane17.setViewportView(mostrar_dic);

        getContentPane().add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 160, 200));

        busq_gen.setText("Búsqueda general");
        busq_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busq_genActionPerformed(evt);
            }
        });
        getContentPane().add(busq_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        busq_esp.setText("Búsqueda específica");
        getContentPane().add(busq_esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        guardar_dic.setText("Guardar diccionario");
        getContentPane().add(guardar_dic, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 160, -1));

        cargar_dic.setText("Cargar diccionario");
        cargar_dic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_dicActionPerformed(evt);
            }
        });
        getContentPane().add(cargar_dic, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 160, -1));

        arbol_bfs.setText("Arbol de recorrido BFS");
        getContentPane().add(arbol_bfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 160, -1));

        palabra_arbol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        palabra_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabra_arbolActionPerformed(evt);
            }
        });
        getContentPane().add(palabra_arbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 70, -1));

        palabra_busq.setText("jTextField1");
        getContentPane().add(palabra_busq, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 90, -1));

        DFS.setText("DFS");
        getContentPane().add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        BFS.setText("BFS");
        getContentPane().add(BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        letra1.setBackground(new java.awt.Color(121, 124, 126));
        letra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra1.setText("jLabel1");
        letra1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        letra2.setBackground(new java.awt.Color(121, 124, 126));
        letra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra2.setText("jLabel1");
        letra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 50, 50));

        letra3.setBackground(new java.awt.Color(121, 124, 126));
        letra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra3.setText("jLabel1");
        letra3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 50, 50));

        letra4.setBackground(new java.awt.Color(121, 124, 126));
        letra4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra4.setText("jLabel1");
        letra4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 50, 50));

        letra5.setBackground(new java.awt.Color(121, 124, 126));
        letra5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra5.setText("jLabel1");
        letra5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 50));

        letra6.setBackground(new java.awt.Color(121, 124, 126));
        letra6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra6.setText("jLabel1");
        letra6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 50, 50));

        letra7.setBackground(new java.awt.Color(121, 124, 126));
        letra7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra7.setText("jLabel1");
        letra7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 50));

        letra8.setBackground(new java.awt.Color(121, 124, 126));
        letra8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra8.setText("jLabel1");
        letra8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 50));

        letra9.setBackground(new java.awt.Color(121, 124, 126));
        letra9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra9.setText("jLabel1");
        letra9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 50, 50));

        letra10.setBackground(new java.awt.Color(121, 124, 126));
        letra10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra10.setText("jLabel1");
        letra10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 50, 50));

        letra11.setBackground(new java.awt.Color(121, 124, 126));
        letra11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra11.setText("jLabel1");
        letra11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 50, 50));

        letra12.setBackground(new java.awt.Color(121, 124, 126));
        letra12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra12.setText("jLabel1");
        letra12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 50, 50));

        letra13.setBackground(new java.awt.Color(121, 124, 126));
        letra13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra13.setText("jLabel1");
        letra13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, 50));

        letra14.setBackground(new java.awt.Color(121, 124, 126));
        letra14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra14.setText("jLabel1");
        letra14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 50, 50));

        letra15.setBackground(new java.awt.Color(121, 124, 126));
        letra15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra15.setText("jLabel1");
        letra15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 50, 50));

        letra16.setBackground(new java.awt.Color(121, 124, 126));
        letra16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra16.setText("jLabel1");
        letra16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(letra16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palabra_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabra_arbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabra_arbolActionPerformed

    private void busq_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busq_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busq_genActionPerformed

    private void cargar_dicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_dicActionPerformed
        String aux = "";
        String texto = "";
        try{
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            File archivo = file.getSelectedFile();
            if(archivo != null){
                FileReader archivo_2 = new FileReader(archivo);
                BufferedReader lee = new BufferedReader (archivo_2);
                while();
                /**hay que rellenar con la iteracion*/
            }
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex+"" "\nNo se ha encontrado el archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_cargar_dicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz_grafos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFS;
    private javax.swing.JButton DFS;
    private javax.swing.JButton arbol_bfs;
    private javax.swing.JCheckBox busq_esp;
    private javax.swing.JCheckBox busq_gen;
    private javax.swing.JButton cargar_dic;
    private javax.swing.JButton guardar_dic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JLabel letra1;
    private javax.swing.JLabel letra10;
    private javax.swing.JLabel letra11;
    private javax.swing.JLabel letra12;
    private javax.swing.JLabel letra13;
    private javax.swing.JLabel letra14;
    private javax.swing.JLabel letra15;
    private javax.swing.JLabel letra16;
    private javax.swing.JLabel letra2;
    private javax.swing.JLabel letra3;
    private javax.swing.JLabel letra4;
    private javax.swing.JLabel letra5;
    private javax.swing.JLabel letra6;
    private javax.swing.JLabel letra7;
    private javax.swing.JLabel letra8;
    private javax.swing.JLabel letra9;
    private javax.swing.JTextArea mostrar_dic;
    private javax.swing.JComboBox<String> palabra_arbol;
    private javax.swing.JTextField palabra_busq;
    // End of variables declaration//GEN-END:variables
}
